kernels:
  # renovate: datasource=docker depName=quay.io/lvh-images/kind
  rhel8.10: 'static-stack-liveness-20260409.124322-amd64'
  # renovate: datasource=docker depName=quay.io/lvh-images/kind
  5.15: 'static-stack-liveness-20260409.124322-amd64'
  # renovate: datasource=docker depName=quay.io/lvh-images/kind
  6.1: 'static-stack-liveness-20260409.124322-amd64'
  # renovate: datasource=docker depName=quay.io/lvh-images/kind
  6.6: 'static-stack-liveness-20260409.124322-amd64'
  # renovate: datasource=docker depName=quay.io/lvh-images/kind
  6.12: 'static-stack-liveness-20260409.124322-amd64'
  # renovate: datasource=docker depName=quay.io/lvh-images/kind
  6.18: 'static-stack-liveness-20260409.124322-amd64'
